### ISSUE TITLE
Personalise plot tracks

### ISSUE THREAD

**Issue by stefanucci-luca** [kevinrue/TVTB#5]
Dear Kevin,

Is it already possible to personalise the graphic of a plot in TVTB?
For instance, as it happens in Gviz?

Best,
Luca

**Comment by kevinrue** [comment]
Dear @stefanucci-luca 

Thanks for your interest.

Unfortunately, at this point in time it is not possible to pass additional arguments to the `plotInfo()` function.

If you want to have a go at adding arguments (perhaps through an ellipsis `...`), I welcome pull requests.
Also, if you submit a minimal reproducible example, it would be easier to see the kind of scenario that you mean.

Best
Kevin
