### ISSUE TITLE
heads-up for filter classes being removed from ensembldb

### ISSUE THREAD

**Issue by jotsetung** [kevinrue/TVTB#5]
Just wanted to give a heads-up that the filter classes previously defined in `ensembldb` will move to the `AnnotationFilter` package (https://github.com/Bioconductor/AnnotationFilter), possibly within the next few days (mainly depends when the `AnnotationFilter` package gets added to Bioconductor).

For your package that means mainly that you will have to import (once I'm done with moving the filter classes) the `GRangesFilter` and the `GenenameFilter` from the `AnnotationFilter` and not the `ensembldb` package. Apart from that I didn't see any changes needed.

Let me know if you need any help or run into issues.

**Comment by kevinrue** [comment]
Heads up much appreciated!

I'll wait on the daunting 'build failed' message from BioC to apply the changes on my side.
Even if it is (/should be) a simple change I think it's cleanest this way: I'll have a log of the breaking change, and I'll be able to test locally the correct changes to apply before pushing them.

...for a second there, I had the crazy idea that I could coordinate and synchronise my changes with yours, within the same daily build, but that would be an ugly mess on my end if I anything goes wrong ;)

All the best!

**Comment by jotsetung** [comment]
I'll let you know before I push the changes, or actually once I did.
I think we can manage without any build error ;)

**Comment by kevinrue** [comment]
True: actually, I can probably `devtools:: install_github` from your GitHub repo to apply the changes and testing within the same BioC daily build.
Anyway, I'll wait on your smoke signal :) 🌨 ☁️ ☁️

**Comment by kevinrue** [comment]
Hi @jotsetung ,

It seems other [breaking changes](http://bioconductor.org/checkResults/devel/bioc-LATEST/TVTB/malbec2-buildsrc.html) have taken place in packages higher up in our chain of dependencies. TVTB (and ensembldb, and many others)'s builds on the level branch failed with error message:

    Error : object ‘inverted’ is not exported by 'namespace:Biostrings'

However, TVTB does not (directly) import or use the `inverted` method; it seems the Biostrings package itself [fails the build](http://bioconductor.org/checkResults/devel/bioc-LATEST/Biostrings/). No doubt that's going to climb high up very fast in the to-do list of the core team.

**Comment by jotsetung** [comment]
Ah, I like the busy times before a new release... This was definitely not my fault - I didn't change anything yet. Looks like `GenomicFeatures` causes the problems. Let's hope this gets fixed soon.

Something similar will happen when I start changing stuff ;)

**Comment by jotsetung** [comment]
OK, `AnnotationFilter` is in Bioc devel. You can go ahead to change the imports of `GenenameFilter` and `GRangesFilter` (classes and constructor functions) from `AnnotationFilter` instead of `ensembldb`. I'll update `ensembldb` tomorrow, so things will start to happen ;)

**Comment by kevinrue** [comment]
Thanks.

@m.lawrence may be able to help on this one:

Something funky is going on. Although I think it is not related to your ensembldb/AnnotationFilter changes, but rather to other packages
After applying exactly the change that you mentioned, R CMD check fails with this message:

    Quitting from lines 570-577 (Introduction.Rmd) 
    Error: processing vignette 'Introduction.Rmd' failed with diagnostics:
    unused argument (condition = "overlapping")
    Execution halted

I don't call this `condition = "overlapping"` in my code, so it must be either `S4Vectors::subsetByFilter`, or `GenomicRanges::range`, or one of their own sub functions  that needs update (my biocValid returns TRUE).

(Kind of) surprisingly, when I run the vignette manually, it fails earlier (lines 465-471) with error:

    Error in (function (cl, name, valueClass) : assignment of an object of class "NULL" is not valid
    for @'elementMetadata' in an object of class "VcfFixedRules";
    is(value, "DataTableORNULL") is not TRUE

First, I'm no expert in the `setClassUnion()` function, but that error message seems to contradict itself basically "is(NULL, "DataTableORNULL") is not TRUE". Anyway, my VCF filter rules inherit all the way to `S4Vectors::Vector` class, which declares:

    setClass("Vector",
      contains="Annotated",
      representation(
          "VIRTUAL",
          elementMetadata="DataTableORNULL"   <----- see here
      )
    )
    
I'll keep digging a bit, but if issues have appeared in my dependencies, the nightly build log may help pinpoint the actual source.

Thanks for the message though!
Kevin

**Comment by jotsetung** [comment]
No, that's related to my code. The `GRangesFilter` doesn't support the `condition` parameter, but it's called now `type`. In addition, `"overlapping"` is no longer supported too. The `GRangesFilter` now uses (to be consistent with `GenomicAlignments`) `type = "any"` (is the same as the `condition = "overlapping"), `type = "within"`, `type = "start"`, `type = "end"` and `type = "equal"`.
This error will be fixed (I hope) once I'll push my changes in `ensembldb` too.
